"""Constants for Concierge."""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "concierge"
NAME = "Concierge"

DEFAULT_NAME = "Concierge"
DEFAULT_UPDATE_INTERVAL_SECONDS = 60
DEFAULT_NIGHT_MODE_ENABLED = False

CONF_UPDATE_INTERVAL_SECONDS = "update_interval_seconds"
CONF_NIGHT_MODE_ENABLED = "night_mode_enabled"

COORDINATOR_TIMEOUT_SECONDS = 10
COORDINATOR_MIN_UPDATE_SECONDS = 15
COORDINATOR_MAX_UPDATE_SECONDS = 3600

STORAGE_VERSION = 1
STORAGE_KEY = f"{DOMAIN}_foundation"

SIGNAL_READY = "ready"
SIGNAL_DEGRADED = "degraded"

# Phase 0 voice enrollment architecture scaffolding constants.
VOICE_ENROLLMENT_MANIFEST_SCHEMA_VERSION = 1

# Approved lifecycle states from HTBW voice enrollment lifecycle architecture.
VOICE_ENROLLMENT_STATE_IDLE = "idle"
VOICE_ENROLLMENT_STATE_PREFLIGHT_VALIDATING = "preflight_validating"
VOICE_ENROLLMENT_STATE_PREFLIGHT_FAILED = "preflight_failed"
VOICE_ENROLLMENT_STATE_SESSION_CREATED = "session_created"
VOICE_ENROLLMENT_STATE_READY = "ready"
VOICE_ENROLLMENT_STATE_CAPTURE_PENDING = "capture_pending"
VOICE_ENROLLMENT_STATE_CAPTURING = "capturing"
VOICE_ENROLLMENT_STATE_SAMPLE_RECEIVED = "sample_received"
VOICE_ENROLLMENT_STATE_PROCESSING = "processing"
VOICE_ENROLLMENT_STATE_PROFILE_BUILDING = "profile_building"
VOICE_ENROLLMENT_STATE_COMPLETED_PENDING_CLEANUP = "completed_pending_cleanup"
VOICE_ENROLLMENT_STATE_CANCELLED_PENDING_CLEANUP = "cancelled_pending_cleanup"
VOICE_ENROLLMENT_STATE_FAILED_PENDING_CLEANUP = "failed_pending_cleanup"
VOICE_ENROLLMENT_STATE_TIMEOUT_PENDING_CLEANUP = "timeout_pending_cleanup"
VOICE_ENROLLMENT_STATE_CLEANUP_RUNNING = "cleanup_running"
VOICE_ENROLLMENT_STATE_CLEANUP_COMPLETE = "cleanup_complete"
VOICE_ENROLLMENT_STATE_CLEANUP_FAILED = "cleanup_failed"

VOICE_ENROLLMENT_LIFECYCLE_STATES: tuple[str, ...] = (
	VOICE_ENROLLMENT_STATE_IDLE,
	VOICE_ENROLLMENT_STATE_PREFLIGHT_VALIDATING,
	VOICE_ENROLLMENT_STATE_PREFLIGHT_FAILED,
	VOICE_ENROLLMENT_STATE_SESSION_CREATED,
	VOICE_ENROLLMENT_STATE_READY,
	VOICE_ENROLLMENT_STATE_CAPTURE_PENDING,
	VOICE_ENROLLMENT_STATE_CAPTURING,
	VOICE_ENROLLMENT_STATE_SAMPLE_RECEIVED,
	VOICE_ENROLLMENT_STATE_PROCESSING,
	VOICE_ENROLLMENT_STATE_PROFILE_BUILDING,
	VOICE_ENROLLMENT_STATE_COMPLETED_PENDING_CLEANUP,
	VOICE_ENROLLMENT_STATE_CANCELLED_PENDING_CLEANUP,
	VOICE_ENROLLMENT_STATE_FAILED_PENDING_CLEANUP,
	VOICE_ENROLLMENT_STATE_TIMEOUT_PENDING_CLEANUP,
	VOICE_ENROLLMENT_STATE_CLEANUP_RUNNING,
	VOICE_ENROLLMENT_STATE_CLEANUP_COMPLETE,
	VOICE_ENROLLMENT_STATE_CLEANUP_FAILED,
)

# Cleanup result taxonomy for idempotent cleanup manager outcomes.
VOICE_ENROLLMENT_CLEANUP_RESULT_COMPLETE = "complete"
VOICE_ENROLLMENT_CLEANUP_RESULT_ALREADY_CLEAN = "already_clean"
VOICE_ENROLLMENT_CLEANUP_RESULT_PARTIAL = "partial"
VOICE_ENROLLMENT_CLEANUP_RESULT_FAILED = "failed"

VOICE_ENROLLMENT_CLEANUP_RESULTS: tuple[str, ...] = (
	VOICE_ENROLLMENT_CLEANUP_RESULT_COMPLETE,
	VOICE_ENROLLMENT_CLEANUP_RESULT_ALREADY_CLEAN,
	VOICE_ENROLLMENT_CLEANUP_RESULT_PARTIAL,
	VOICE_ENROLLMENT_CLEANUP_RESULT_FAILED,
)

VOICE_ENROLLMENT_CLEANUP_STATUS_NOT_STARTED = "not_started"
VOICE_ENROLLMENT_CLEANUP_STATUS_PENDING = "cleanup_pending"
VOICE_ENROLLMENT_CLEANUP_STATUS_RUNNING = "cleanup_running"
VOICE_ENROLLMENT_CLEANUP_STATUS_COMPLETE = "cleanup_complete"
VOICE_ENROLLMENT_CLEANUP_STATUS_FAILED = "cleanup_failed"

VOICE_ENROLLMENT_CLEANUP_STATUSES: tuple[str, ...] = (
	VOICE_ENROLLMENT_CLEANUP_STATUS_NOT_STARTED,
	VOICE_ENROLLMENT_CLEANUP_STATUS_PENDING,
	VOICE_ENROLLMENT_CLEANUP_STATUS_RUNNING,
	VOICE_ENROLLMENT_CLEANUP_STATUS_COMPLETE,
	VOICE_ENROLLMENT_CLEANUP_STATUS_FAILED,
)

VOICE_ENROLLMENT_CLEANUP_REASON_COMPLETED = "completed"
VOICE_ENROLLMENT_CLEANUP_REASON_CANCELLED = "cancelled"
VOICE_ENROLLMENT_CLEANUP_REASON_FAILED = "failed"
VOICE_ENROLLMENT_CLEANUP_REASON_TIMEOUT = "timeout"
VOICE_ENROLLMENT_CLEANUP_REASON_MANUAL = "manual"
VOICE_ENROLLMENT_CLEANUP_REASON_UNKNOWN = "unknown"

VOICE_ENROLLMENT_CLEANUP_REASONS: tuple[str, ...] = (
	VOICE_ENROLLMENT_CLEANUP_REASON_COMPLETED,
	VOICE_ENROLLMENT_CLEANUP_REASON_CANCELLED,
	VOICE_ENROLLMENT_CLEANUP_REASON_FAILED,
	VOICE_ENROLLMENT_CLEANUP_REASON_TIMEOUT,
	VOICE_ENROLLMENT_CLEANUP_REASON_MANUAL,
	VOICE_ENROLLMENT_CLEANUP_REASON_UNKNOWN,
)

# Repairs issue ids aligned to HTBW enrollment architecture.
VOICE_ENROLLMENT_REPAIRS_STORAGE_MISSING = "voice_enrollment_storage_missing"
VOICE_ENROLLMENT_REPAIRS_STORAGE_UNAVAILABLE = "voice_enrollment_storage_unavailable"
VOICE_ENROLLMENT_REPAIRS_STORAGE_NOT_WRITABLE = "voice_enrollment_storage_not_writable"
VOICE_ENROLLMENT_REPAIRS_STORAGE_MISCONFIGURED = "voice_enrollment_storage_misconfigured"
VOICE_ENROLLMENT_REPAIRS_STORAGE_RECORDER_CONFLICT = "voice_enrollment_storage_recorder_conflict"
VOICE_ENROLLMENT_REPAIRS_STORAGE_PROBE_FAILED = "voice_enrollment_storage_probe_failed"
VOICE_ENROLLMENT_REPAIRS_CLEANUP_FAILED = "voice_enrollment_cleanup_failed"
VOICE_ENROLLMENT_REPAIRS_ORPHAN_CLEANUP_FAILED = "voice_enrollment_orphan_cleanup_failed"
VOICE_ENROLLMENT_REPAIRS_INVALID_MANIFEST = "voice_enrollment_invalid_manifest"
VOICE_ENROLLMENT_REPAIRS_CAPTURE_PROVIDER_UNAVAILABLE = "voice_enrollment_capture_provider_unavailable"
VOICE_ENROLLMENT_REPAIRS_CAPTURE_PROVIDER_UNSUPPORTED = "voice_enrollment_capture_provider_unsupported"
VOICE_ENROLLMENT_REPAIRS_SELECTED_SATELLITE_UNAVAILABLE = "voice_enrollment_selected_satellite_unavailable"

VOICE_ENROLLMENT_REPAIRS_ISSUE_IDS: tuple[str, ...] = (
	VOICE_ENROLLMENT_REPAIRS_STORAGE_MISSING,
	VOICE_ENROLLMENT_REPAIRS_STORAGE_UNAVAILABLE,
	VOICE_ENROLLMENT_REPAIRS_STORAGE_NOT_WRITABLE,
	VOICE_ENROLLMENT_REPAIRS_STORAGE_MISCONFIGURED,
	VOICE_ENROLLMENT_REPAIRS_STORAGE_RECORDER_CONFLICT,
	VOICE_ENROLLMENT_REPAIRS_STORAGE_PROBE_FAILED,
	VOICE_ENROLLMENT_REPAIRS_CLEANUP_FAILED,
	VOICE_ENROLLMENT_REPAIRS_ORPHAN_CLEANUP_FAILED,
	VOICE_ENROLLMENT_REPAIRS_INVALID_MANIFEST,
	VOICE_ENROLLMENT_REPAIRS_CAPTURE_PROVIDER_UNAVAILABLE,
	VOICE_ENROLLMENT_REPAIRS_CAPTURE_PROVIDER_UNSUPPORTED,
	VOICE_ENROLLMENT_REPAIRS_SELECTED_SATELLITE_UNAVAILABLE,
)

# P0-06 preflight failure taxonomy (no repairs publishing in this phase).
VOICE_ENROLLMENT_PREFLIGHT_STORAGE_NOT_CONFIGURED = "storage_not_configured"
VOICE_ENROLLMENT_PREFLIGHT_STORAGE_MISSING = "storage_missing"
VOICE_ENROLLMENT_PREFLIGHT_STORAGE_UNAVAILABLE = "storage_unavailable"
VOICE_ENROLLMENT_PREFLIGHT_STORAGE_NOT_WRITABLE = "storage_not_writable"
VOICE_ENROLLMENT_PREFLIGHT_STORAGE_POLICY_DENIED = "storage_policy_denied"
VOICE_ENROLLMENT_PREFLIGHT_STORAGE_RECORDER_CONFLICT = "storage_recorder_conflict"
VOICE_ENROLLMENT_PREFLIGHT_STORAGE_CONFIG_CONFLICT = "storage_config_conflict"
VOICE_ENROLLMENT_PREFLIGHT_STORAGE_PROBE_FAILED = "storage_probe_failed"
VOICE_ENROLLMENT_PREFLIGHT_STORAGE_UNKNOWN_FAILURE = "storage_unknown_failure"

VOICE_ENROLLMENT_PREFLIGHT_FAILURE_CODES: tuple[str, ...] = (
	VOICE_ENROLLMENT_PREFLIGHT_STORAGE_NOT_CONFIGURED,
	VOICE_ENROLLMENT_PREFLIGHT_STORAGE_MISSING,
	VOICE_ENROLLMENT_PREFLIGHT_STORAGE_UNAVAILABLE,
	VOICE_ENROLLMENT_PREFLIGHT_STORAGE_NOT_WRITABLE,
	VOICE_ENROLLMENT_PREFLIGHT_STORAGE_POLICY_DENIED,
	VOICE_ENROLLMENT_PREFLIGHT_STORAGE_RECORDER_CONFLICT,
	VOICE_ENROLLMENT_PREFLIGHT_STORAGE_CONFIG_CONFLICT,
	VOICE_ENROLLMENT_PREFLIGHT_STORAGE_PROBE_FAILED,
	VOICE_ENROLLMENT_PREFLIGHT_STORAGE_UNKNOWN_FAILURE,
)

SERVICE_EXECUTE = "execute"
SERVICE_EXECUTE_DIRECT = "execute_direct"
SERVICE_GET_INTERACTIONS = "get_interactions"
SERVICE_UPDATE_INTERACTION = "update_interaction"
SERVICE_CLEAR_INTERACTION = "clear_interaction"
SERVICE_GET_SIGNAL = "get_signal"
SERVICE_GET_SIGNALS = "get_signals"
SERVICE_UPDATE_ROOM_CONFIG = "update_room_config"
SERVICE_UPDATE_GLOBAL_CONTEXT = "update_global_context"
SERVICE_UPDATE_EXECUTION_PREFERENCES = "update_execution_preferences"
SERVICE_UPDATE_COMPOSITE_CONFIG = "update_composite_config"
SERVICE_UPDATE_PERSON_PROFILE = "update_person_profile"
SERVICE_UPDATE_VOICE_PROFILE = "update_voice_profile"
SERVICE_START_VOICE_ENROLLMENT = "start_voice_enrollment"
SERVICE_CAPTURE_VOICE_ENROLLMENT_SAMPLE = "capture_voice_enrollment_sample"
SERVICE_REMOVE_VOICE_ENROLLMENT_SAMPLE = "remove_voice_enrollment_sample"
SERVICE_BUILD_VOICE_PROFILE = "build_voice_profile"
SERVICE_RESET_VOICE_PROFILE = "reset_voice_profile"
SERVICE_DELETE_VOICE_PROFILE = "delete_voice_profile"
SERVICE_SYNC_COMPOSITES = "sync_composites"
SERVICE_GET_CONTEXT = "get_context"
SERVICE_GET_SUMMARY = "get_summary"
SERVICE_PREVIEW_TTS_VOICE = "preview_tts_voice"
SERVICE_UPDATE_IDENTITY_PROFILE = "update_identity_profile"
SERVICE_SYNC_ROOMS = "sync_rooms"
SERVICE_REFRESH_ENTITY_STRUCTURE = "refresh_entity_structure"
SERVICE_RECORD_ACTIVITY_EVENT = "record_activity_event"
SERVICE_CLOSE_ACTIVITY_OUTCOME = "close_activity_outcome"
SERVICE_GET_ACTIVITY_TIMELINE = "get_activity_timeline"
SERVICE_EXPORT_ACTIVITY_ARCHIVE = "export_activity_archive"
SERVICE_RESOLVE_MOBILE_CONTEXT = "resolve_mobile_context"
SERVICE_PUSH_PERSON_MESSAGE = "push_person_message"

EVENT_EXECUTION = "concierge_execution"

VOICE_SYSTEM_DEFAULT = "system_default"

TTS_PROVIDER_ENTITY_IDS = {
	"openai_conversation": "tts.openai_tts",
	"google_translate": "tts.google_translate_en_com",
}

UPDATE_INTERVAL_FALLBACK = timedelta(seconds=DEFAULT_UPDATE_INTERVAL_SECONDS)
